--liquibase formatted sql

--changeset sargon:04-00-init
--comment: The tables this service owns. The schema itself is provisioning, not
--comment: migration: scripts/db-provision-roles.sh creates it, and the service role has
--comment: no CREATE on the database — so it cannot reach into a neighbour's schema.

create table notification_service.device_tokens (id bigint generated by default as identity, created_at timestamp(6) with time zone not null, platform varchar(255) not null check ((platform in ('ANDROID','IOS','WEB'))), token varchar(255) not null, user_id uuid not null, primary key (id), constraint idx_device_tokens_token unique (token));
create index idx_device_tokens_user_id on notification_service.device_tokens (user_id);
