--liquibase formatted sql

--changeset sargon:00-init-schema splitStatements:true endDelimiter:;
--comment: Complete initial schema (schemas + all tables), ported from the original Flyway V1__Init.sql


CREATE SCHEMA IF NOT EXISTS user_service;
CREATE SCHEMA IF NOT EXISTS inventory_service;
CREATE SCHEMA IF NOT EXISTS chat_service;
CREATE SCHEMA IF NOT EXISTS notification_service;
CREATE SCHEMA IF NOT EXISTS quote_service;

CREATE TABLE user_service.email_verification_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id    UUID                                    NOT NULL,
    used_at    TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_email_verification_tokens PRIMARY KEY (id)
);

CREATE TABLE user_service.password_reset_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    user_id    UUID                                    NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    used_at    TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (id)
);

CREATE TABLE user_service.refresh_tokens
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      UUID                                    NOT NULL,
    hashed_token VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE user_service.users
(
    id                  UUID         NOT NULL,
    email               VARCHAR(255) NOT NULL,
    username            VARCHAR(255) NOT NULL,
    hashed_password     VARCHAR(255) NOT NULL,
    has_verified_email  BOOLEAN      NOT NULL,
    first_name          VARCHAR(255) NOT NULL,
    last_name           VARCHAR(255) NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    profile_picture_url VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE user_service.email_verification_tokens
    ADD CONSTRAINT uc_email_verification_tokens_token UNIQUE (token);

ALTER TABLE user_service.password_reset_tokens
    ADD CONSTRAINT uc_password_reset_tokens_token UNIQUE (token);

ALTER TABLE user_service.users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE user_service.users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE UNIQUE INDEX idx_password_reset_token_token ON user_service.password_reset_tokens (token);

CREATE INDEX idx_refresh_tokens_user_id ON user_service.refresh_tokens (user_id);

CREATE INDEX idx_refresh_tokens_user_token ON user_service.refresh_tokens (user_id, hashed_token);

CREATE UNIQUE INDEX idx_users_email ON user_service.users (email);

CREATE UNIQUE INDEX idx_users_username ON user_service.users (username);

ALTER TABLE user_service.email_verification_tokens
    ADD CONSTRAINT FK_EMAIL_VERIFICATION_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES user_service.users (id);

ALTER TABLE user_service.password_reset_tokens
    ADD CONSTRAINT FK_PASSWORD_RESET_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES user_service.users (id);

CREATE TABLE inventory_service.article_variant_attributes
(
    variant_id      UUID         NOT NULL,
    attribute_value VARCHAR(255),
    attribute_key   VARCHAR(255) NOT NULL,
    CONSTRAINT pk_article_variant_attributes PRIMARY KEY (variant_id, attribute_key)
);

CREATE TABLE inventory_service.article_variant_dimensions
(
    variant_id UUID NOT NULL,
    label      VARCHAR(255),
    width_cm   DOUBLE PRECISION,
    height_cm  DOUBLE PRECISION,
    depth_cm   DOUBLE PRECISION,
    weight_kg  DOUBLE PRECISION
);

CREATE TABLE inventory_service.article_variants
(
    id               UUID         NOT NULL,
    sku              VARCHAR(255) NOT NULL,
    name             VARCHAR(255) NOT NULL,
    description      TEXT,
    image_url        VARCHAR(255),
    is_active        BOOLEAN      NOT NULL,
    stock            INTEGER      NOT NULL,
    rental_price     DECIMAL(19, 4),
    sale_price       DECIMAL(19, 4),
    replacement_cost DECIMAL(19, 4),
    article_id       UUID,
    CONSTRAINT pk_article_variants PRIMARY KEY (id)
);

CREATE TABLE inventory_service.articles
(
    id                   UUID         NOT NULL,
    name_template        VARCHAR(255) NOT NULL,
    description_template TEXT,
    is_active            BOOLEAN      NOT NULL,
    type                 VARCHAR(255) NOT NULL,
    category_id          UUID,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_articles PRIMARY KEY (id)
);

CREATE TABLE inventory_service.categories
(
    id          UUID         NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    icon_name   VARCHAR(255),
    is_active   BOOLEAN,
    parent_id   UUID,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE inventory_service.discounts
(
    id                 UUID           NOT NULL,
    name               VARCHAR(255)   NOT NULL,
    description        TEXT,
    type               VARCHAR(255)   NOT NULL,
    value              DECIMAL(19, 4) NOT NULL,
    start_date         TIMESTAMP WITHOUT TIME ZONE,
    end_date           TIMESTAMP WITHOUT TIME ZONE,
    is_active          BOOLEAN        NOT NULL,
    target_category_id UUID,
    target_article_id  UUID,
    target_variant_id  UUID,
    priority           INTEGER        NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_discounts PRIMARY KEY (id)
);

ALTER TABLE inventory_service.articles
    ADD CONSTRAINT FK_ARTICLES_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES inventory_service.categories (id);

ALTER TABLE inventory_service.article_variants
    ADD CONSTRAINT FK_ARTICLE_VARIANTS_ON_ARTICLE FOREIGN KEY (article_id) REFERENCES inventory_service.articles (id);

ALTER TABLE inventory_service.categories
    ADD CONSTRAINT FK_CATEGORIES_ON_PARENT FOREIGN KEY (parent_id) REFERENCES inventory_service.categories (id);

ALTER TABLE inventory_service.article_variant_attributes
    ADD CONSTRAINT fk_article_variant_attributes_on_article_variant_entity FOREIGN KEY (variant_id) REFERENCES inventory_service.article_variants (id);

ALTER TABLE inventory_service.article_variant_dimensions
    ADD CONSTRAINT fk_article_variant_dimensions_on_article_variant_entity FOREIGN KEY (variant_id) REFERENCES inventory_service.article_variants (id);

CREATE TABLE chat_service.chat_messages
(
    id         UUID NOT NULL,
    content    TEXT NOT NULL,
    chat_id    UUID NOT NULL,
    sender_id  UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_chat_messages PRIMARY KEY (id)
);

CREATE TABLE chat_service.chat_participants
(
    user_id             UUID         NOT NULL,
    username            VARCHAR(255) NOT NULL,
    email               VARCHAR(255) NOT NULL,
    profile_picture_url TEXT,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_chat_participants PRIMARY KEY (user_id)
);

CREATE TABLE chat_service.chat_participants_cross_ref
(
    chat_id        UUID NOT NULL,
    participant_id UUID NOT NULL,
    CONSTRAINT pk_chat_participants_cross_ref PRIMARY KEY (chat_id, participant_id)
);

CREATE TABLE chat_service.chats
(
    id         UUID NOT NULL,
    creator_id UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_chats PRIMARY KEY (id)
);

ALTER TABLE chat_service.chat_participants
    ADD CONSTRAINT uc_chat_participants_email UNIQUE (email);

ALTER TABLE chat_service.chat_participants
    ADD CONSTRAINT uc_chat_participants_username UNIQUE (username);

CREATE INDEX idx_chat_message_chat_id_created_at ON chat_service.chat_messages (chat_id, created_at DESC);

CREATE UNIQUE INDEX idx_chat_participant_email ON chat_service.chat_participants (email);

CREATE UNIQUE INDEX idx_chat_participant_username ON chat_service.chat_participants (username);

ALTER TABLE chat_service.chats
    ADD CONSTRAINT FK_CHATS_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES chat_service.chat_participants (user_id);

ALTER TABLE chat_service.chat_messages
    ADD CONSTRAINT FK_CHAT_MESSAGES_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat_service.chats (id) ON DELETE CASCADE;

ALTER TABLE chat_service.chat_messages
    ADD CONSTRAINT FK_CHAT_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES chat_service.chat_participants (user_id);

ALTER TABLE chat_service.chat_participants_cross_ref
    ADD CONSTRAINT fk_chaparcroref_on_chat_entity FOREIGN KEY (chat_id) REFERENCES chat_service.chats (id);

ALTER TABLE chat_service.chat_participants_cross_ref
    ADD CONSTRAINT fk_chaparcroref_on_chat_participant_entity FOREIGN KEY (participant_id) REFERENCES chat_service.chat_participants (user_id);

CREATE TABLE notification_service.device_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    UUID                                    NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    platform   VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_device_tokens PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_device_tokens_token ON notification_service.device_tokens (token);

CREATE INDEX idx_device_tokens_user_id ON notification_service.device_tokens (user_id);

CREATE TABLE quote_service.quote_items
(
    id         UUID           NOT NULL,
    quote_id   UUID,
    variant_id UUID,
    quantity   INTEGER        NOT NULL,
    unit_price DECIMAL(19, 4) NOT NULL,
    added_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_quote_items PRIMARY KEY (id)
);

CREATE TABLE quote_service.quotes
(
    id               UUID                        NOT NULL,
    client_id        UUID                        NOT NULL,
    status           VARCHAR(255)                NOT NULL,
    event_start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    venue_address    VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_quotes PRIMARY KEY (id)
);

ALTER TABLE quote_service.quote_items
    ADD CONSTRAINT FK_QUOTE_ITEMS_ON_QUOTE FOREIGN KEY (quote_id) REFERENCES quote_service.quotes (id);

ALTER TABLE quote_service.quote_items
    ADD CONSTRAINT FK_QUOTE_ITEMS_ON_VARIANT FOREIGN KEY (variant_id) REFERENCES inventory_service.article_variants (id);