--liquibase formatted sql

--changeset sargon:04-01-init
--comment: The tables this service owns. The schema itself is provisioning, not
--comment: migration: scripts/db-provision-roles.sh creates it, and the service role has
--comment: no CREATE on the database.

create table user_service.email_verification_tokens (id bigint generated by default as identity, created_at timestamp(6) with time zone not null, expires_at timestamp(6) with time zone not null, token varchar(255) not null unique, used_at timestamp(6) with time zone, pending_registration_id uuid not null, primary key (id));
create table user_service.password_reset_tokens (id bigint generated by default as identity, created_at timestamp(6) with time zone not null, expires_at timestamp(6) with time zone not null, token varchar(255) not null unique, used_at timestamp(6) with time zone, user_id uuid not null, primary key (id));
create table user_service.pending_registrations (id uuid not null, created_at timestamp(6) with time zone not null, email varchar(255) not null unique, expires_at timestamp(6) with time zone not null, hashed_password varchar(255) not null, username varchar(255) not null unique, verified_at timestamp(6) with time zone, primary key (id));
create table user_service.refresh_tokens (id bigint generated by default as identity, created_at timestamp(6) with time zone not null, hashed_token varchar(255) not null, updated_at timestamp(6) with time zone not null, user_id uuid not null, primary key (id));
create table user_service.users (id uuid not null, created_at timestamp(6) with time zone not null, email varchar(255) not null unique, first_name varchar(255) not null, has_verified_email boolean not null, hashed_password varchar(255) not null, last_name varchar(255) not null, profile_picture_url varchar(255), updated_at timestamp(6) with time zone not null, username varchar(255) not null unique, primary key (id));
create index idx_refresh_tokens_user_id on user_service.refresh_tokens (user_id);
create index idx_refresh_tokens_user_token on user_service.refresh_tokens (user_id, hashed_token);
alter table if exists user_service.email_verification_tokens add constraint FK26k27o0wya3yc422l5jmj7dqf foreign key (pending_registration_id) references user_service.pending_registrations;
alter table if exists user_service.password_reset_tokens add constraint FKk3ndxg5xp6v7wd4gjyusp15gq foreign key (user_id) references user_service.users;
